version: "3.8"

services: 
  generator:
    build:
      context: .
    image: aspnetcore/generator:multi
    ports: 
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports: 
      - "8025:8025"