# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

WORKDIR /api

COPY api.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -o /publish

# Runtime Image Stage
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /publish
COPY --from=build-env /publish .
ENTRYPOINT [ "dotnet", "api.dll" ]