version: '3.8'

services: 
    my-registry:
        image: registry:latest
        volumes: 
            - registry:/var/lib/registry
        ports: 
            - "55000:5000"
        restart: unless-stopped


volumes: 
    registry: