version: '3.8'

services: 
    teamcity:
        image: jetbrains/teamcity-server:2019.2.4
        volumes: 
            - teamcity-server-datadir:/data/teamcity_server/datadir
            - teamcity_server-logs:/opt/teamcity/logs
        ports: 
            - 8111:8111
    teamcity-agent:
        image: jetbrains/teamcity-agent:2019.2.4
        environment: 
            SERVER_URL: http://teamcity:8111
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock

volumes: 
    teamcity-server-datadir:
    teamcity_server-logs: